services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dappnet
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
    environment:
      - PORT=3000

  ui:
    build: ./ui
    ports:
      - "8080:80"
    networks:
      - dappnet
    environment:
      - VITE_API_URL=http://api:3000

networks:
  dappnet:
    driver: bridge
