services:
  api:
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
    networks:
      - dappnet
    healthcheck:
      test: curl -f http://localhost:${API_PORT}/health || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${API_PORT}
      - DOCKER_SOCKET_PATH=${DOCKER_SOCKET}

  ui:
    build: ./ui
    ports:
      - "${UI_PORT}:80"
    networks:
      - dappnet
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=http://api:${API_PORT}
      - NODE_ENV=${NODE_ENV}

networks:
  dappnet:
    driver: bridge
